### ISSUE TITLE
new API for InnateDB

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#17] opened 2019-11-19 17:29 UTC
https://www.innatedb.com/

Innate immunity interactions

**Comment by ericz1803** [comment] 2022-08-01 20:29
Example documents: 
```json
{
    "subject": {
        "unique_identifier": "innatedb:IDBG-25842",
        "alt_identifier": "ensembl:ENSG00000154589",
        "alias": "uniprotkb:LY96_HUMAN|refseq:NP_056179|uniprotkb:Q9Y6Y9|refseq:NP_001182726|hgnc:LY96(display_short)",
        "ncbi_taxid": "taxid:9606(Human)",
        "biological_role": "psi-mi:\"MI:0499\"(unspecified role)",
        "exp_role": "psi-mi:\"MI:0498\"(prey)",
        "interactor_type": "psi-mi:\"MI:0326\"(protein)",
        "participant_identification_method": "psi-mi:\"MI:0363\"(inferred by author)"
    },
    "object": {
        "unique_identifier": "innatedb:IDBG-82738",
        "alt_identifier": "ensembl:ENSG00000136869",
        "alias": "refseq:NP_612564|refseq:NP_612567|uniprotkb:O00206|uniprotkb:TLR4_HUMAN|refseq:NP_003257|hgnc:TLR4(display_short)",
        "ncbi_taxid": "taxid:9606(Human)",
        "biological_role": "psi-mi:\"MI:0499\"(unspecified role)",
        "exp_role": "psi-mi:\"MI:0496\"(bait)",
        "interactor_type": "psi-mi:\"MI:0326\"(protein)",
        "participant_identification_method": "psi-mi:\"MI:0363\"(inferred by author)"
    },
    "relation": {
        "interaction_detection_method": "psi-mi:\"MI:0007\"(anti tag coimmunoprecipitation)",
        "author": "Shimazu et al. (1999)",
        "pmid": "pubmed:10359581",
        "interaction_type": "psi-mi:\"MI:0915\"(physical association)",
        "source_database": "MI:0974(innatedb)",
        "idinteraction_in_source_db": "innatedb:IDB-113240",
        "confidence_score": "lpr:3|hpr:3|np:1|",
        "ncbi_taxid_host_organism": "taxid:10090",
        "creation_date": "2008/03/30",
        "update_date": "2008/03/30",
        "negative": "false"
    },
    "_id": "innatedb:IDBG-25842-innatedb:IDBG-82738"
}
{
    "subject": {
        "unique_identifier": "innatedb:IDBG-28022",
        "alt_identifier": "ensembl:ENSG00000198001",
        "alias": "uniprotkb:IRAK4_HUMAN|uniprotkb:Q9NWZ3|refseq:NP_001138728|refseq:NP_001138729|refseq:NP_001107654|refseq:NP_001138730|refseq:NP_057207|hgnc:IRAK4(display_short)",
        "ncbi_taxid": "taxid:9606(Human)",
        "biological_role": "psi-mi:\"MI:0501\"(enzyme)",
        "exp_role": "psi-mi:\"MI:0499\"(unspecified role)",
        "interactor_type": "psi-mi:\"MI:0326\"(protein)",
        "participant_identification_method": "psi-mi:\"MI:0363\"(inferred by author)"
    },
    "object": {
        "unique_identifier": "innatedb:IDBG-28022",
        "alt_identifier": "ensembl:ENSG00000198001",
        "alias": "uniprotkb:IRAK4_HUMAN|uniprotkb:Q9NWZ3|refseq:NP_001138728|refseq:NP_001138729|refseq:NP_001107654|refseq:NP_001138730|refseq:NP_057207|hgnc:IRAK4(display_short)",
        "ncbi_taxid": "taxid:9606(Human)",
        "biological_role": "psi-mi:\"MI:0502\"(enzyme target)",
        "exp_role": "psi-mi:\"MI:0499\"(unspecified role)",
        "interactor_type": "psi-mi:\"MI:0326\"(protein)",
        "participant_identification_method": "psi-mi:\"MI:0363\"(inferred by author)"
    },
    "relation": {
        "interaction_detection_method": "psi-mi:\"MI:0423\"(in-gel kinase assay)",
        "author": "Cheng et al. (2007)",
        "pmid": "pubmed:17141195",
        "interaction_type": "psi-mi:\"MI:0217\"(phosphorylation reaction)",
        "source_database": "MI:0974(innatedb)",
        "idinteraction_in_source_db": "innatedb:IDB-113326",
        "confidence_score": "lpr:1|hpr:1|np:1|",
        "ncbi_taxid_host_organism": "taxid:7108",
        "creation_date": "2008/09/28",
        "update_date": "2008/09/28",
        "negative": "false"
    },
    "_id": "innatedb:IDBG-28022-innatedb:IDBG-28022"
}
```

Statistics for interaction_type:
```
{
'psi-mi:"MI:0915"(physical association)': 31086, 
'psi-mi:"MI:0217"(phosphorylation reaction)': 1201, 
'psi-mi:"MI:0220"(ubiquitination reaction)': 423, 
'psi-mi:"MI:0570"(protein cleavage)': 324, 
'psi-mi:"MI:0194"(cleavage reaction)': 147, 
'psi-mi:"MI:0203"(dephosphorylation reaction)': 40, 
'psi-mi:"MI:0179"(other modification)': 14, 
'psi-mi:"MI:0566"(sumoylation)': 9, 
'psi-mi:"MI:0408"(disulfide bond)': 8, 
'psi-mi:"MI:0204"(deubiquitination reaction)': 7, 
'psi-mi:"MI:0401"(biochemical)': 6, 
'psi-mi:"MI:0213"(methylation reaction)': 6, 
'psi-mi:"MI:0414"(enzymatic reaction)': 6, 
'psi-mi:"MI:0192"(acetylation reaction)': 5, 
'psi-mi:"MI:0195"(covalent binding)': 5, 
'psi-mi:"MI:0566"(sumoylation reaction)': 3, 
'psi-mi:"MI:0914"(association)': 2, 
'psi-mi:"MI:1126"(self interaction)': 2,
'psi-mi:"MI:0557"(adp ribosylation reaction)': 1
}
```

**Comment by colleenXu** [comment] 2022-08-01 20:52
I think someone else (Andrew?) should take the lead on changes. 

I have some thoughts but I don't know if others would agree (starting with the subject section first)

Subject:
* change subject.unique_identifier -> subject.innatedb. Then remove "innatedb:" prefix from the value. 
* change subject.alt_identifier -> subject.ensembl. Then remove "ensembl:" prefix from the value
* break down the "alias" value (currently a string) and turn it into an object (note that I concatenated for keys that are the same and changed some key names):
```
"subject": {
    "alias": {
        "uniprotkb_name": "LY96_HUMAN",
        "refseq": ["NP_056179", "NP_001182726"],
        "uniprotkb_id": "Q9Y6Y9",
        "hgnc_name": "LY96(display_short)"
    }
}
```
* change value for subject.ncbi_taxid to just have the ID: subject.ncbi_taxid: "9606"
* change the rest of the properties to separate the "id" from the prefix and label (aka human readable thing)
```
"subject": {
    "biological_role": {
        "psi-mi": "MI:0499",
        "label": "unspecified role"
    },
    "exp_role": {
        "psi-mi": "MI:0498",
        "label": "prey"
    },
    "interactor_type": {
        "psi-mi": "MI:0326",
        "label": "protein"
    },
    "participant_identification_method": {
        "psi-mi": "MI:0363",
        "label": "inferred by author"
    },
}
```

**Comment by colleenXu** [comment] 2022-08-01 21:07
Relation 

* change relation.interaction_detection_method / relation.interaction_type to separate the "id" from the prefix and label (aka human readable thing) (similar to the "other properties" above)
```
"relation": {
    "interaction_detection_method": {
        "psi-mi": "MI:0007",
        "label": "anti tag coimmunoprecipitation"
    },
    "interaction_type": {
        "psi-mi": "MI:0915",
        "label": "physical association"
    }
}
```
* relation.pmid: remove the "pubmed:" prefix from the value. 
* handle source database stuff differently (1 object):
```
"relation": {
    "source_database": {
        "id": "MI:0974",
        "label": "innatedb",
        "interaction_id": "IDB-113240"
    }
}
```
* break down the "alias" value (currently a string) and turn it into an object (then the numbers can be int)
```
"relation": {
    "confidence_score": {
        "lpr": 3,
        "hpr": 3,
        "np": 1
    }
}
```
* change value for relation.ncbi_taxid_host_organism to just have the ID. So it'd be `"relation": {"ncbi_taxid_host_organism": "10090" }`
* change date format to YYYY-MM-DD (aka use dashes, not slashes)? so `2008-03-30`

---

_id: be careful of using _ids like this....are there records that might end up with the same _ids (since their subject/object IDs are the same?). Also use a different "delimiter" since the IDs already have dashes in them....maybe `_`?

**Comment by ericz1803** [comment] 2022-08-02 23:31
I made the changes. The only difference is I slightly modified the `alias` field to look like:
```
"alias": {
    "refseq": [
        "NP_004336"
    ],
    "uniprotkb": [
        "P49913"
    ],
    "uniprotkb_name": "CAMP_HUMAN",
    "hgnc_name": "CAMP"
},
```

**Comment by ericz1803** [comment] 2022-08-09 21:48
Deployed.

**Comment by ericz1803** [comment] 2022-08-10 16:02
API link: https://biothings.ncats.io/innatedb

**Comment by andrewsu** [comment] 2022-08-24 15:55
Per https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/README-contributing-new-data-source.md, the next step would be to write the SmartAPI metadata file.  @ericz1803 do you want to take a crack at that? Or have you tried and hit problems?

**Comment by colleenXu** [comment] 2023-12-05 06:04
I wrote the [SmartAPI yaml w/ x-bte annotation for BioThings InnateDB](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/innatedb/smartapi.yaml). 

<details><summary>Noting some decisions I made</summary>
<p>

* ~93% of the records have the interaction_type [physical_association](https://biothings.ncats.io/innatedb/query?q=relation.interaction_type.label:%22physical%20association%22) (31086/33295)
* I also wrote [operations](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L310) for 5 other interaction_types with > 10 records (excluding "other modification" because I wasn't sure what it meant). Ref: [the list of interaction_type values at the bottom of this comment](https://github.com/biothings/pending.api/issues/17#issuecomment-1201684667)
    * but for now, they all use physically_interacts_with as the biolink predicate (+ no qualifiers)...because I had trouble figuring out how to map them
    * biolink-model qualifiers are only for chem-affects-gene and gene-regulates-gene, but this data seems like protein-protein interactions
    * it's not clear if the data has directionality (ex: is it "subject ubiquinates object" or vice versa?)
        * I have notes from my analysis of the subject/object biological role values for each interaction_type (ex: [here](https://github.com/NCATS-Tangerine/translator-api-registry)). /blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L694) for phosphorylation)
        * I think directionality was clear when the biological role combo was enzyme/enzyme-target, enzyme-target/enzyme, or self/self
        * but this wasn't useful for [ubiquitination](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L764) where unspecified-role/unspecified-role seemed most common
* for now, for all operations I used ENSEMBL (ENSG) IDs and assigned all categories as Gene (reasoning on lines [586](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L586)-591)
    * but the physical_association data included different subject/object interactor_type values (protein vs dna vs rna). Noted [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L592) and [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L627) in case we want to use them in the future. 
* I included my notes on other fields I thought could be useful, as yaml comments starting on line [599](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L599)

</p>
</details> 

This yaml is [registered in SmartAPI Registry](https://smart-api.info/registry?q=e9eb40ff7ad712e4e6f4f04b964b5966) and the [PR to add this KP to BTE's regular use is here](https://github.com/biothings/bte-server/pull/2). 

I tested the PR locally and the SmartAPI yaml/x-bte annotation works. 

<details><summary>Example test</summary>
<p>

send a POST request to the api-specific endpoint, BioThings TTD only. Like `http://localhost:3000/v1/smartapi/e9eb40ff7ad712e4e6f4f04b964b5966/query`

Put this in the request body: It's querying with the gene PIK3C3 (aka `NCBIGene:5289`)

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["ENSEMBL:ENSG00000078142"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

You should get a response with this edge (from this [set of records from the BioThings API](https://biothings.ncats.io/innatedb/query?q=relation.interaction_type.label:%22physical%20association%22%20AND%20subject.alt_identifier.ensembl:ENSG00000078142%20AND%20object.alt_identifier.ensembl:ENSG00000126775)), based on this [operation's example](https://github.com/NCATS-Tangerine/translator-api-registry/blob/49030afd133688184ec193bffb827c47a540ab4f/innatedb/smartapi.yaml#L658):
* subject: PIK3C3 aka `NCBIGene:5289`, `ENSEMBL:ENSG00000078142`
* object: ATG14 aka `NCBIGene:22863`, `ENSEMBL:ENSG00000126775`

```
                "352f144dd72e3f14f4fd4d628e73b552": {
                    "predicate": "biolink:physically_interacts_with",
                    "subject": "NCBIGene:5289",
                    "object": "NCBIGene:22863",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:18843052",
                                "PMID:19050071"
                            ],
                            "value_type_id": "linkml:Uriorcurie"
                        }
                    ],
                    "sources": [
                        {
                            "resource_id": "infores:innatedb",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-innatedb",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:innatedb"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-innatedb"
                            ]
                        }
                    ]
                },
```

</p>
</details>

**Comment by colleenXu** [comment] 2023-12-05 06:06
Related infores stuff is ready but not deployed yet:
* new infores catalog entries for innatedb and biothings-innatedb [in my fork](https://github.com/colleenXu/biolink-model/commit/b0538872aeb4483100836bcb975b475eee6ecf55)
* made new infores pages for [innatedb (primary knowledge source)](https://github.com/NCATSTranslator/Translator-All/wiki/InnateDB) and [biothings-innatedb (placeholder)](https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-InnateDB-API)

**Comment by colleenXu** [comment] 2024-02-21 09:26
Closing this issue since the changes have been deployed to Prod with the Feb 2024 release. 

I've confirmed that I can query BioThings InnateDB through BTE prod https://bte.transltr.io/v1/smartapi/e9eb40ff7ad712e4e6f4f04b964b5966/query with the example in https://github.com/biothings/pending.api/issues/17#issuecomment-1840068479 and get the expected response.

**Closed by colleenXu** 2024-02-21 09:26 UTC
Labels: data source, x-bte, On Test, api deployment done
