### ISSUE TITLE
Data source: DDInter

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#68] opened 2022-06-01 05:24 UTC
name: Curated Drug-Drug Interactions Database
url: http://ddinter.scbdd.com/
download: http://ddinter.scbdd.com/download/
license: CC-BY-NC-SA (http://ddinter.scbdd.com/terms/)

**Comment by mnarayan1** [comment] 2022-06-07 00:09
I can claim this ticket.

**Comment by andrewsu** [comment] 2022-06-09 04:37
emailed data owners to ask about providing mappings between DDinterIDs and DrugBank/ChEMBL/PubChem.

**Comment by mnarayan1** [comment] 2022-06-23 10:46
[Here's](https://github.com/mnarayan1/DDInter/blob/main/parser.py) a parser I wrote with the data that's available so far.

**Comment by mnarayan1** [comment] 2022-08-01 00:38
I was able to scrape additional information (PubChem, ChEMBL, DrugBank ids) from http://ddinter.scbdd.com/. 

Web scraper: https://github.com/mnarayan1/DDInter/blob/main/webscraper.py
Scraped drug information (used directly in the parser): https://github.com/mnarayan1/DDInter/blob/main/drug_data.json

Updated parser: https://github.com/mnarayan1/DDInter/blob/main/parser.py
Sample output file: https://github.com/mnarayan1/DDInter/blob/main/ddinter_data.json

Sample Record: 
```
{
   "_id":"DDInter1263_DDInter1_Moderate",
   "drug_a":{
      "ddinterid_a":"DDInter1263",
      "name":"Naltrexone",
      "chembl":"CHEMBL19019",
      "pubchem":"5360515",
      "drugbank":"DB00704"
   },
   "drug_b":{
      "ddinterid_b":"DDInter1",
      "name":"Abacavir",
      "chembl":"CHEMBL1380",
      "pubchem":"441300",
      "drugbank":"DB01048"
   },
   "level":"Moderate"
}
```

**Comment by andrewsu** [comment] 2022-08-01 19:00
@mnarayan1 in https://github.com/mnarayan1/DDInter/blob/main/webscraper.py#L7, you hard code a range on DDInter identifiers.  Is it possible to generalize that so that your parser would work seamlessly when/if DDInter is updated?  Thinking of iterating until you get a 404, or perhaps basing the scaping based on DDInter values in the downloadable file?

**Comment by mnarayan1** [comment] 2022-08-02 19:53
I've updated the scraper to iterate until a page doesn't exist. Let me know if there's anything else I should fix.

**Comment by andrewsu** [comment] 2022-08-02 21:20
Have you confirmed that all of the IDs run continuously with no interruption?  For example, is there ever the case where DDInter1234 was retired or for some reason doesn't exist?

**Comment by mnarayan1** [comment] 2022-08-03 16:20
So far, all of the IDs exist and run continuously.

**Comment by andrewsu** [comment] 2022-08-03 18:49
great, I think this data plugin is ready for @erikyao to deploy.  In parallel, you can also start working on writing the SmartAPI / OpenAPI annotation, as described in https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/README-writing-x-bte.md.  That guide is a work in progress, so suggestions on improvements are welcome and questions can go to Colleen and/or Rohan.

**Comment by erikyao** [comment] 2022-08-09 22:47
Hi @andrewsu, I am testing the parser and I think the field names `"ddinterid_a"` and `"ddinterid_b"` could be better named `"ddinterid"`, or more simply `"ddinter"`. What do you think? Thanks!

**Comment by andrewsu** [comment] 2022-08-09 23:41
Great point and good catch. Yes, let's go with `ddinter`. Thanks!

**Comment by erikyao** [comment] 2022-08-10 03:18
Hi @mnarayan1, I found multiple documents with `{'_id': 'DDInter424_DDInter7_Major'}`. Please let me know when you fix the issue. Thanks!

P.S. I have forked your repo to https://github.com/biothings/DDInter and made some changes. Please let me know if you want to work directly on that fork (I can make a PR on your request).

**Comment by mnarayan1** [comment] 2022-08-10 20:49
@erikyao I updated my parser, so hopefully the problem should be fixed. Could you make a pull request so I can update my repo with the changes you made? Thanks!

**Comment by erikyao** [comment] 2022-08-10 21:26
@mnarayan1 Please find the PR at https://github.com/mnarayan1/DDInter/pull/1. Thanks!

**Comment by andrewsu** [comment] 2022-09-21 18:31
the PR above was merged and [deployed](https://biothings.ncats.io/ddinter/metadata). Next step is to write SmartAPI / x-bte annotation.

**Comment by andrewsu** [comment] 2022-12-19 16:14
As noted in the [linked issue just above](https://github.com/NCATSTranslator/Feedback/issues/62):
> The list of downloadable files at http://ddinter.scbdd.com/download/ appears to be incomplete. For example, the interaction noted by @karafecho above (http://ddinter.scbdd.com/ddinter/interact/1002248/) is not found in any of the linked files, but it is found in the unlinked http://ddinter.scbdd.com/static/media/download/ddinter_downloads_code_N.csv file

I think this parser should be updated to download and process all files corresponding to `http://ddinter.scbdd.com/static/media/download/ddinter_downloads_code_[A-Z].csv`

**Comment by mnarayan1** [comment] 2022-12-27 05:16
I updated the [parser ](https://github.com/mnarayan1/DDInter/blob/main/parser.py#L10-L18) to download all the files in `http://ddinter.scbdd.com/static/media/download/ddinter_downloads_code_[A-Z].csv`. Some letters don't seem to have a file (ex. there is no `ddinter_downloads_code_E`).

**Comment by colleenXu** [comment] 2023-01-03 23:13
Checking with @mnarayan1 @andrewsu :
* It sounds like we'll want to update / re-deploy this API?
* I wonder if we can get more information, like:
    * the Interaction ID. We can then use it to construct linkouts to the database like http://ddinter.scbdd.com/ddinter/interact/1047495/ (either in the biothings API or in jq annotation for BTE)
    * the mechanism (aka what is the interaction caused by). See this [page](http://ddinter.scbdd.com/ddinter/drug-detail/DDInter1064/) for an example of a drug's interactions that show many different mechanism categories. 
    * description of the interaction, references, alternatives for either drug, possible metabolism interactions. These are sections of interesting data that can be seen on a webpage for an interaction: http://ddinter.scbdd.com/ddinter/interact/981427/

**Comment by tokebe** [comment] 2023-01-25 19:40
This API has been deployed to Prod, should the issue be closed?

**Comment by colleenXu** [comment] 2023-01-27 07:36
Yep, closing it now

**Closed by colleenXu** 2023-01-27 07:36 UTC
Labels: data source
