### ISSUE TITLE
Data source: RARe-SOURCE

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#109] opened 2023-03-20 16:39 UTC
A gene-disease association knowledge source focused on rare diseases.

https://raresource.nih.gov/

Data files can be downloaded *manually* via the "export" button on each browsing page.

**Comment by erikyao** [comment] 2023-04-01 07:54
Data plugin repo: https://github.com/biothings/rare_source

API published to https://biothings.ncats.io/rare_source
ITRB CI is not working so it's not shown in the API list on the index page.

**Comment by colleenXu** [comment] 2023-04-11 19:59
Next steps are creating SmartAPI yaml w/ x-bte annotation, registering it, adding it to the API_LIST (for full ingest). Want this process done by Mid-May. 

Looks like example TRAPI queries will be Gene <-> Disease...

<details><summary>Discussion from Slack</summary>

> Chunlei: 
> Yao deployed a new rare_source knowledge API last week at https://biothings.ncats.io/rare_source. It's organized by genes, and then the associated rare disease info is included as `raresource.disease` field. A few example queries:
> * https://biothings.ncats.io/rare_source/gene/9211
> * https://biothings.ncats.io/rare_source/query?q=hgnc:28434
> * https://biothings.ncats.io/rare_source/query?q=raresource.disease.name:%22Triple%20A%20syndrome%22
> * https://biothings.ci.transltr.io/rare_source/query?q=raresource.disease.umls:C3150902
>
> This is a requested source by Tyler from this NIH resource: https://raresource.nih.gov/. If the returned data objects look good to us, the next step is to add a SmartAPI metadata and annotations of its gene-disease association, so it's integrated into BTE.

> Andrew:
> can you create an issue for the smartAPI annotation and the example TRAPI query?  We can prioritize that at our next meeting.  Chunlei, if you have thoughts on priority (aside from the fact that Tyler requested it), let us know...

> Chunlei: 
> I also msg'ed Tyler for the priority, I assume it won't be too urgent, unless he has a direct use case depending on it.

> Chunlei: 
> mid-May seems plenty of time for us.
> From Tylor (looks like this was a request from Christine originally):
> after checking in with Christine, she would like it if we could have the bulk of the RARESource data integrated into the system by mid-May. Would that be doable?

</details>

**Comment by colleenXu** [comment] 2023-05-12 02:02
SmartAPI yaml with x-bte annotation created https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/ncats_rare_source/smartapi.yaml. Link above is to hook it up with BTE

### NOTE

Because of the entity-based structure (organized by gene), basic querying doesn't accurately grab the cooccurrence_url when querying from disease -> gene (reverse, related to https://github.com/biothings/biothings_explorer/issues/316). So we don't have that field when querying in this reverse direction. 

However, @newgene says there is a new way of advanced querying that can help with this...

### EXAMPLES

Responses are TRAPI 1.3.

<details><summary>Example query (gene -> disease)</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:100"],
                    "categories": ["biolink:Gene"],
                    "name": "ADA"
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            }
        }
    }
}
```

</details> 

<details><summary>Response's edge from RARe-SOURCE, with cooccurrence url</summary>

```
                "7d4a84de4a253d7d998db33e4c9bd74f": {
                    "predicate": "biolink:gene_associated_with_condition",
                    "subject": "NCBIGene:100",
                    "object": "MONDO:0011338",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:primary_knowledge_source",
                            "value": [
                                "infores:rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:biothings-rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "https://raresource.nih.gov/literature/cooccurrence/RMRP/0008198"
                            ]
                        }
                    ]
                },
```

</details> 


<details><summary>Example query (disease -> gene) - REVERSE </summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["OMIM:615994"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

</details> 

<details><summary>Response's edge from RARe-SOURCE, WITHOUT cooccurrence url</summary>

```
                "b5be16227d3e2e684adf46cede21ff1a": {
                    "predicate": "biolink:condition_associated_with_gene",
                    "subject": "MONDO:0014445",
                    "object": "NCBIGene:10806",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:primary_knowledge_source",
                            "value": [
                                "infores:rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:biothings-rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        }
                    ]
                },
                "cbef74226734679888067ff0e39593d1": {
                    "predicate": "biolink:condition_associated_with_gene",
                    "subject": "MONDO:0014445",
                    "object": "NCBIGene:11020",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:primary_knowledge_source",
                            "value": [
                                "infores:rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        },
                        {
                            "attribute_type_id": "biolink:aggregator_knowledge_source",
                            "value": [
                                "infores:biothings-explorer",
                                "infores:biothings-rare-source"
                            ],
                            "value_type_id": "biolink:InformationResource"
                        }
                    ]
                },
```

</details>

**Comment by colleenXu** [comment] 2023-05-12 02:11
### NOTE 2

@newgene @erikyao 

There seems to be some errors in the data/parser for the co-occurrence urls. 

In the [BioThings API entry for the gene ADA](https://biothings.ncats.io/rare_source/query?q=entrezgene:100), the first hit's co-occurrence url is incorrect. It should have the term "ADA" in the url, aka it should be `https://raresource.nih.gov/literature/cooccurrence/ADA/0008198`. Instead it is `https://raresource.nih.gov/literature/cooccurrence/RMRP/0008198`. 

I noticed this since I was reviewing/pasting the examples above (this is related to the first example).

**Comment by colleenXu** [comment] 2023-05-12 02:29
### NOTE 3

Current limitations -> needs followup with SRI team

#### Disease IDs

The x-bte annotation doesn't allow BTE to retrieve all 2901 (gene-centric) records, because 55 records lack ORPHANET disease IDs (there may be more records affected but it's hard to tell because of the gene-centric records). ORPHANET was the ID-namespace with the 2nd-best coverage.

VS all records seemed to have GARD Disease IDs, but SRI Node Normalizer appears to have no support for this ID-namespace. Biolink-model also doesn't mention GARD as an ID-namespace. 

Other options are:
* OMIM - 2774
* UMLS - 2529
* MESH - 1450
* ICD10-CM - 7

#### infores IDs

The infores for the BioThings API and original resource (RARe-SOURCE) are not in the infores registry tsv yet. Going to try adding them soon.

**Comment by erikyao** [comment] 2023-05-12 02:46
Hi @colleenXu, `NOTE 2` is caused by shallow copying, will fix asap.

**Comment by newgene** [comment] 2023-05-12 17:30
Thanks @colleenXu, for Note 3, I will pass the feedback to Tyler too, in addition to SRI team, who might be able to reach out the GARD team see if they have ID xrefs available already.

**Comment by erikyao** [comment] 2023-05-15 21:09
Hi @colleenXu, `NOTE 2` problem fixed. Thanks for pointing it out.

**Comment by colleenXu** [comment] 2023-05-17 05:56
Updated SmartAPI yaml and registration to support UMLS Disease IDs and Gene names (when this is the output of the operation). https://github.com/NCATS-Tangerine/translator-api-registry/commit/03ca46040b1f02664f8aa048a404d0258c2a5832

This was done after discussion with @andrewsu on Monday, when we discovered that we may be able to use UMLS Disease IDs to cover the gap in record retrieval in [Note 3](https://github.com/biothings/pending.api/issues/109#issuecomment-1545017362). 

---

### Note 4

While testing this, I discovered that SRI Node Normalizer doesn't have much support for some NCBIGene IDs (doesn't retrieve names or many equivalent IDs): for example these 4 genes are found in this resource but [their names aren't retrieved by Node Norm prod](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=NCBIGene%3A105259599&curie=NCBIGene%3A100188767&curie=NCBIGene%3A114086&curie=NCBIGene%3A1275&conflate=true). It could be because these genes aren't protein-coding or are only loci linked to the diseases (rather than a more-defined genomic entity)
* [H19-ICR](https://www.ncbi.nlm.nih.gov/gene/105259599)
* [AGSPX](https://www.ncbi.nlm.nih.gov/gene/100188767)
* [DBA2](https://www.ncbi.nlm.nih.gov/gene/114086)
* [COD2](https://www.ncbi.nlm.nih.gov/gene/1275)

This is why I added support for Gene names for Disease->Gene operations

### Note 5

However, when I tried to add support for Gene names for Gene->Disease operations, all the co-occurrence URLs would appear on every Edge, when they're supposed to show up only on the edge they correspond to (a specific gene-disease pair). 

This seems to be unrelated to the addition of the UMLS Disease operations. If I:
* comment out their refs in /query (so I only have the gene-diseaseOrphanet and its counterpart operation)
* add `symbol` to the parameter.fields of gene-diseaseOrphanet
* add `input_name: symbol` to the `diseaseOrphanet-object` x-bte-response-mapping...
* I end up with edges with all the co-occurrence urls like below 

<details><summary>edge would look like this when doing Example 1</summary>

This should only have the first url, not the second (that's part of a diff record/gene-disease pair...)

```
                "7d4a84de4a253d7d998db33e4c9bd74f": {
                    "predicate": "biolink:gene_associated_with_condition",
                    "subject": "NCBIGene:100",
                    "object": "MONDO:0011338",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "https://raresource.nih.gov/literature/cooccurrence/ADA/0008198",
                                "https://raresource.nih.gov/literature/cooccurrence/ADA/0005748"
                            ]
                        }
                    ],
                    "sources": [
                        {
                            "resource_id": "infores:rare-source",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-rare-source",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:rare-source"
                            ]
                        },
                        {
                            "resource_id": "infores:biothings-explorer",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-rare-source"
                            ]
                        }
                    ]
                },
```

</details>

**Comment by colleenXu** [comment] 2023-05-22 19:17
Closing because all BTE instances have access to this API now. Will open new issue if there are updates to the Notes (1 reverses, 4 NCBIGene, 5 - bug). 

(2 BioThings data is addressed, 3 GARD - Chunlei has reported on this and infores is done)

**Closed by colleenXu** 2023-05-22 19:17 UTC
Labels: data source
